// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slqujnnsfjavvlneyuiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNscXVqbm5zZmphdnZsbmV5dWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODM3MjgsImV4cCI6MjA3MjY1OTcyOH0.bGiHeWyxMu0l9qhXOdPDrG6ZJNt7mtpO8mMipWSQByQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});